---
extends: default

rules:
  document-start: disable
  comments-indentation: disable
  line-length:
    max: 150
    level: warning
  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
