"""add congregation groups

Revision ID: faecec299731
Revises: 0007
Create Date: 2026-03-08 01:24:33.292513

"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faecec299731"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "congregation_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("district_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["district_id"], ["districts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "calendar_integrations",
        "credentials_enc",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_calendar_integrations_district_id"), table_name="calendar_integrations")
    op.add_column("congregations", sa.Column("group_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "congregations", "congregation_groups", ["group_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(
        op.f("ix_events_external_uid"),
        table_name="events",
        postgresql_where="(external_uid IS NOT NULL)",
    )
    op.drop_constraint(op.f("export_tokens_token_key"), "export_tokens", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("export_tokens_token_key"),
        "export_tokens",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_events_external_uid"),
        "events",
        ["calendar_integration_id", "external_uid"],
        unique=True,
        postgresql_where="(external_uid IS NOT NULL)",
    )
    op.drop_constraint(None, "congregations", type_="foreignkey")
    op.drop_column("congregations", "group_id")
    op.create_index(
        op.f("ix_calendar_integrations_district_id"),
        "calendar_integrations",
        ["district_id"],
        unique=False,
    )
    op.alter_column(
        "calendar_integrations",
        "credentials_enc",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_table("congregation_groups")
    # ### end Alembic commands ###
